version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: moviedb
    volumes:
      - mongo_data:/data/db

  moviemanagement:
    build: .
    container_name: moviemanagement
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/moviedb
    depends_on:
      - mongodb

volumes:
  mongo_data:
